### ISSUE TITLE
Fix security vulnerability in package-lock.json 

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias-display#28]
The security warning has been reported by github: https://github.com/IntegratedAlarmSystem-Group/ias-display/network/dependencies

**Comment by sfehlandt** [comment]
We upgraded one of the affected packages: jquery.

For the other one we need to upgrade to Angular 6, which was scheduled to be done for Release 4.

**Comment by sfehlandt** [comment]
**Current status**
Unfortunately there is not much we can do about this, since the affected libraries are dependencies of dependencies, and we cannot control which versions of their dependencies our dependencies use.

The affected libraries were fixed and their dependants were updates accordingly up to "request v2.83".

The problem is that there are still 2 packages in our dependency tree using versions of "request" prior to 2.83:

* **node-sass:** We are using their latest version, 4.9.0, which uses request 2.79. Currently the team is working on v5 which will use request 2.85. This is not merged yet because it will loose compatibility with node < 4, and hence it will be done for the next non-backwards-compatible release (v5)

* **loggly:** Here the dependecy is lower in the tree: karma@2.0.2 -> logs4js@2.8.0 -> loggly@1.1.1. The problem is that loggly@1.1.1 is still using request 2.75. The project has not been updated in 2 years. So there is not much hope this will be fixed any time soon.

**The bright side**
These are only "devDependencies", which mean they are only used for either testing or building the application and not in runtime. Specifically, the code of these dependencies does not go in the final application, it will not be in the docker images, and thus it will not be an issue for the production environment.

**Next Steps**
* Wait until node-sass is updated: https://github.com/sass/node-sass/issues/2355

* Wait until loggly is updated: https://github.com/winstonjs/node-loggly/issues/78, https://github.com/winstonjs/node-loggly/issues/71

  - Wait until log4js is updated after loggly: https://github.com/log4js-node/log4js-node/issues/716
  - Wait until karma is updated after log4js: https://github.com/karma-runner/karma/issues/2994

Since this is out of our control we suggest to keep this issue open until the dependencies are updated.
This issue will be removed from the Release 4 milestone: https://github.com/IntegratedAlarmSystem-Group/ias-display/milestone/4

**Comment by sfehlandt** [comment]
Update:
node-sass and log4js have been updated. We only need to wait for karma to update the version of log4js: log4js
