### ISSUE TITLE
Inconsistency between overview and table

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias-display#48]
There is an inconsistency between the weather alarms shown by the overview and those in the table.
The table shows an alarm in this moment:

![table2](https://user-images.githubusercontent.com/8500519/42127728-cffaf07c-7c6b-11e8-81ec-668efd6b6ab6.PNG)

But the overview shows the invalid state instead of begin RED+INVALID as there are invalid monitor points as well as valid ones.

![overview](https://user-images.githubusercontent.com/8500519/42127693-33e16afe-7c6b-11e8-96a7-e9ceaca118f1.PNG)

However, note that now the alarm state changes often between read and green.

**Comment by jmaldonadof** [comment]
This is not a problem of the display, this happens because the ias core is not sending the alarms showed in the overview yet. The display does not process the alarms to determine if there is a problem in any of the weather sensors, instead, it expect to receive three different alarms from the core that indicate that any of the humidity, temperature or windspeed sensors are set. 
For now, if the IAS core sends an iasio of type alarm with core id "WS-Temperature-Global", it will be displayed in the overview. The same for the other 2 type of sensors.

**Comment by acaproni** [comment]
Very good!
I have already configured the CDB with the alarms you are talking about Jazmine, Still the processing from the supervisor is missing.
