### ISSUE TITLE
Add props (map that contains the value) of last update to the Table

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-display#98]

**Comment by acaproni** [comment]
What does this ticket mean?
Is it the value of associated IASIOs that triggered the alarm like for instance the value of a temperature sensor that triggered a temperature alarm?
If it is that then this ticket must be more generic and be something like _let the table show the additional information of alarms_
Additional information are passed as a map whose content depends on the implementation of reduction rules and no assumption can be done on its content (Keys) in the web application.

Additional info should be shown in all the panels, not only in the table. A tooltip coul dbe enough otside of thetable.

**Comment by acaproni** [comment]
I agree to show all the props in the ACK and shelve. For the tooltip we could show only one or two props and allow the operator to see all of them by selecting the tooltip (to be double checked with Grazia for usability/readability).

Your proposal works for just one value  but not if there are many values.
The `ThresholdWithBackupsAndDelay` TF sets the key `value` with the value read from the main WS if it exists; otherwise it returns the key `backup`with the comma separated values of the backups weather stations. With this definition, only one between `value` and `backup` is defined.

**Comment by sfehlandt** [comment]
We talked on a videocon and we decided this:

- Add the full props on the Ack / Shelve Panel
- Add the props on the tooltip (there should be few props)
- Evaluate adding 1 column for props in the Table with 2 options:
  a) Add each prop in a different
  b) Add 1 prop and an icon/button to open the tooltip with the full props
